### ISSUE TITLE
device rename not picked up

### ISSUE THREAD

**Issue by OskarBrink** [lvanderree/com.synplyworks.thenmore#1]
I started to use the app, and it works great, however at some point I changed the name of a lamp and it did not pick up the name change. Even the new name did not appear.
I had to restart the app for it to recognize the new names, whereafter I only than could make the change in the flow cards.

**Comment by lvanderree** [comment]
Found issue, will update it soon

**Comment by lvanderree** [comment]
Fixed in 0.6.0
