### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by Fanman76** [lvanderree/com.synplyworks.thenmore#12]
I'm trying to add a timer card to a flow, to keep a light on when motion is detected. Yet no device can be found in the card.
![Voordeur lamp](https://user-images.githubusercontent.com/48988697/55073749-cb6ce400-508e-11e9-8a8e-d7e10138b688.PNG)

**Comment by Fanman76** [comment]
Solved by installing the beta version

**Comment by lvanderree** [comment]
thanks for the update, I had forgotten about the stable release creating this issue on homey2, but your finding is correct ;-)
