### ISSUE TITLE
Won't start anything anymore

### ISSUE THREAD

**Issue by GrimmJok3r** [lvanderree/com.synplyworks.thenmore#13]
Timers won't start anymore
Running Beta 0.7.2 and Homey 2.1.1

After restarting app still nothing happens.
None of my flows involving the Timer app (almost all my light flows) won't work.

If i need to check something out let me know 
thx

**Comment by GrimmJok3r** [comment]
Just seeing after trying to edit a flow with the timer app.
When trying to change the timer option I get the message in the bottom right corner
"Er is een onbekende fout opgetreden" (Session-Expired)
This is the case with all the flow's involving the Timer App.
Al other flows on Homey work just fine.

Im gonne remove the app and install it again.
Keep you posted

**Comment by GrimmJok3r** [comment]
Unfortunatelly after reinstalling Same issue

Here is the diagnostic rapport code
2919dc36-eeb8-423a-ad6b-661aadc5e3da

**Comment by GrimmJok3r** [comment]
The message above was caused on the flow maker on the compter.
When i do it on the Phone App and i select the the device it needs to change it says No Results
It's like it's not allowed to read the Device info/list from Homey

**Comment by GrimmJok3r** [comment]
As the Wife was kinda annoyed that the lights didn't worked all over the house I changed all my flows to my old system with the Countdown App.

**Comment by lvanderree** [comment]
I guess it is a bug in Homey: 
https://athomcommunity.slack.com/conversation/C04SUGZ9E/p1555516692062000

> WeeJeWel   [Apr 17th at 5:58 PM]
> Workaround: `Homey.sessions.deleteSessions();` in https://developer.athom.com/tools/api-playground. 

Then restart the app


> WeeJeWel [5:57 PM]
> Fixed in the next release :slightly_smiling_face:

(after 2.1.1)

**Comment by GrimmJok3r** [comment]
You my man, are great!!

Will change it all back to Timer next week as we are leaving today for a week of Disney.
Keep you posted.

Thx for the response.
