### ISSUE TITLE
Timer only works one time

### ISSUE THREAD

**Issue by driesk81** [lvanderree/com.synplyworks.thenmore#15]
Thanks for the Timer app. This app should make it so simple to control lights with a motion detector.
Problem is that in my case the app works only one time as intended. After that a restart of the app seems necessarily.
Diagnostic report: 00ff286e-2b36-4129-a6b9-67a141ce5332
Please let me know if the app is still under active development.

**Comment by lvanderree** [comment]
Hi @driesk81 

since the app is working OK, I haven't been developing much on it. However I do take a look at bug reports and fix issues, when I have time and when things go wrong I try to make some time for it.

I looked at your report, but I cannot see what exactly is going on. I don't know if you've seen it yourself, but this is what I've got:


```
2019-10-27 22:27:04 [log] [TimerApp] remember state for Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] (since on and restore on) oldValue 0
2019-10-27 22:27:04 [log] [TimerApp] set device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] capability dim to 0.05
2019-10-27 22:27:04 [log] [TimerApp] set timer for device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] to 60 seconds, oldValue: false
2019-10-27 22:27:26 [log] [TimerApp] Cancelled timer for device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809]

2019-10-27 22:27:29 [log] [TimerApp] remember state for Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] (since on and restore on) oldValue 0.37
2019-10-27 22:27:29 [log] [TimerApp] set device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] capability dim to 0.05
2019-10-27 22:27:29 [log] [TimerApp] set timer for device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] to 60 seconds, oldValue: 0.37
2019-10-27 22:27:36 [log] [TimerApp] Cancelled timer for device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809]
```

You have the lights off, 
- then enable the timer turning a light on (dimmed at 0,05, while it was off), 
- then disable it before the timer ends, 
- then enable it again turning a light on again (dimmed at 0,05, while it was 0,37), 
- then cancel it again

I don't know 
- why you cancel the timer (probably a card somewhere in your flow) 
- and how the light got changed from 0,05 to 0,37

**Comment by driesk81** [comment]
Hoi Leon,

Wat een ongelooflijk snelle reactie.
Je conclusie van de log file (die kan ik zelf niet inzien) is juist.
Ik gebruik inderdaad een flow card om de timer te stoppen als handmatig het dimniveau boven de 5% wordt gezet.

Het lijkt er dus op dat alles naar behoren werkt.
Net nog even getest. De timer app lijkt prima te werken tot ik het dimniveau handmatig omhoog zet als de timer loopt. Als ik dan de lamp uitzet en daarna de bewegingsmelder activeer reageert de timer app niet meer.

Daarna de timer app herstart en alles werkt weer naar behoren. Welke data zou helpen dit probleem te debuggen?

Met vriendelijke groeten
Gijs Driessen

Op 28 okt. 2019, om 20:19, Leon van der Ree <notifications@github.com<mailto:notifications@github.com>> schreef:

Hi @driesk81<https://github.com/driesk81>

since the app is working OK, I haven't been developing much on it. However I do take a look at bug reports and fix issues, when I have time and when things go wrong I try to make some time for it.

I looked at your report, but I cannot see what exactly is going on. I don't know if you've seen it yourself, but this is what I've got:

2019-10-27 22:27:04 [log] [TimerApp] remember state for Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] (since on and restore on) oldValue 0
2019-10-27 22:27:04 [log] [TimerApp] set device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] capability dim to 0.05
2019-10-27 22:27:04 [log] [TimerApp] set timer for device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] to 60 seconds, oldValue: false
2019-10-27 22:27:26 [log] [TimerApp] Cancelled timer for device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809]

2019-10-27 22:27:29 [log] [TimerApp] remember state for Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] (since on and restore on) oldValue 0.37
2019-10-27 22:27:29 [log] [TimerApp] set device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] capability dim to 0.05
2019-10-27 22:27:29 [log] [TimerApp] set timer for device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809] to 60 seconds, oldValue: 0.37
2019-10-27 22:27:36 [log] [TimerApp] Cancelled timer for device Lampen overloop [fc6201b1-5fc7-49d3-be46-13450dab9809]


You have the lights off,

  *   then enable the timer turning a light on (dimmed at 0,05, while it was off),
  *   then disable it before the timer ends,
  *   then enable it again turning a light on again (dimmed at 0,05, while it was 0,37),
  *   then cancel it again

I don't know

  *   why you cancel the timer (probably a card somewhere in your flow)
  *   and how the light got changed from 0,05 to 0,37

**Comment by lvanderree** [comment]
Ok, dus als ik het goed lees verhoog je zelf het dimniveau terwijl de timer loopt, wat er voor zorgt dat de timer gecancelled wordt. Daarna zet je een keer de lamp uit. Vervolgens gaat de timer nooit meer aan.

Dat moet ik denk ik zelf ook kunnen reproduceren. Heb ik alleen niet gelijk tijd voor, maar zal vermoedelijk van de week wel lukken. Waarschijnlijk zit er dan ergens een bug bij de cancel timer functie,waardoor de nieuwe timer niet meer wilt starten.

**Comment by driesk81** [comment]
Dat klopt helemaal.
Pir is een neo coolcam
Lamp fibaro dimmer 2
De achterliggende gedachte is dat als de lamp aan staat de timer functie vanzelfsprekend niet werkt. En als deze toch geactiveerd wordt doordat iemand de sensor passeert en besluit dat de lamp aan moet blijven enkel het dim Nivea moet verhogen boven de 5%

Ik hoor graag of je tot dezelfde conclusie komt en heb geen haast ;-)
Fijne avond.
Op 28 okt. 2019, om 20:56, Leon van der Ree <notifications@github.com<mailto:notifications@github.com>> schreef:

Ok, dus als ik het goed lees verhoog je zelf het dimniveau terwijl de timer loopt, wat er voor zorgt dat de timer gecancelled wordt. Daarna zet je een keer de lamp uit. Vervolgens gaat de timer nooit meer aan.

Dat moet ik denk ik zelf ook kunnen reproduceren. Heb ik alleen niet gelijk tijd voor, maar zal vermoedelijk van de week wel lukken. Waarschijnlijk zit er dan ergens een bug bij de cancel timer functie,waardoor de nieuwe timer niet meer wilt starten.

**Comment by lvanderree** [comment]
Ik kan de situatie reproduceren, en ik had de fout helaas zelf ook al eens ervaren, bleek uit het commentaar in mijn code.

Het probleem ontstaat door een bug in de athom api code, waarmee de device state verkregen wordt, maar welke helaas out of sync kan zijn. 
In dit geval betekend dat, dat als je je lamp met de hand uit zet, de timer app dit niet door krijgt, en voor altijd zal denken dat de lamp aan staat en daardoor werkt het dus inderdaad niet meer. Ik zal gaan kijken of ik deze cache kan overrulen, want homey zelf weet wel degelijk dat de devices uit staan.

**Comment by lvanderree** [comment]
Ik heb denk ik een oplossing om de capabilityValue op een andere manier te verkrijgen, die geen last heeft van de caching. Ik moet dit echt nog wat verder testen en wellicht op meerdere plaatsen toepassen.

Als je weet hoe je apps kunt sideloaden, kan je proberen om branch bugfix/capability te installeren

**Comment by driesk81** [comment]
Hoi Leon

Dat klopt met mijn bevindingen. Ik heb ook nog wat tests gedaan en kwam daarbij tot de conclusie dat handmatige bediening de oorzaak lijkt. Ik had eigenlijk met een andere schakelaar (Qubino ipv fibaro) willen testen en je dan een update willen geven.
Op 2 nov. 2019, om 22:06, Leon van der Ree <notifications@github.com<mailto:notifications@github.com>> schreef:

Ik kan de situatie reproduceren, en ik had de fout helaas zelf ook al eens ervaren, bleek uit het commentaar in mijn code.

Het probleem ontstaat door een bug in de athom api code, waarmee de device state verkregen wordt, maar welke helaas out of sync kan zijn.
In dit geval betekend dat, dat als je je lamp met de hand uit zet, de timer app dit niet door krijgt, en voor altijd zal denken dat de lamp aan staat en daardoor werkt het dus inderdaad niet meer. Ik zal gaan kijken of ik deze cache kan overrulen, want homey zelf weet wel degelijk dat de devices uit staan.

**Comment by driesk81** [comment]
Zal morgen even kijken of ik wat tijd kan vinden. 2 kids onder de 3 jaar ;-)
Op 2 nov. 2019, om 22:34, Leon van der Ree <notifications@github.com<mailto:notifications@github.com>> schreef:

Ik heb denk ik een oplossing om de capabilityValue op een andere manier te verkrijgen, die geen last heeft van de caching. Ik moet dit echt nog wat verder testen en wellicht op meerdere plaatsen toepassen.

Als je weet hoe je apps kunt sideloaden, kan je proberen om branch bugfix/capability te installeren

**Comment by lvanderree** [comment]
top, dat met die kids herken ik, heb er zelf ook 2 waarschijnlijk 1 jaartje ouder. 
Ik heb versie 0.7.3 gemaakt welke nu bij athom ter review ligt
