### ISSUE TITLE
When removing and re-adding "timer" capable device, flow action can't be updated

### ISSUE THREAD

**Issue by shaarkys** [lvanderree/com.synplyworks.thenmore#18]
Hi,
front time to time it's required to simply re-add given devices, which will cause Timer functionality lost, even when using the same name of the device - which is understandable. This is understandable, however after removing and re-adding given device, the problem is that given Timer flow can't be updated - it simply shows empty list, on Flow Web it shows even "Network Request failed". Not sure this is Homey issue or Timer app issue though. The only way is to remove given Timer action and add it from scratch.
Apologies if this is known issue.

![obrazek](https://user-images.githubusercontent.com/14859895/89457529-d006d980-d765-11ea-81aa-f747f8639134.png)
![obrazek](https://user-images.githubusercontent.com/14859895/89457607-ed3ba800-d765-11ea-9b51-ec381192ebe5.png)

**Comment by lvanderree** [comment]
Hi I am sorry it took a while for me to respons.

I understand your problem, but I am afraid I cannot do much about it. The name of a device is only there for the user to recognize it, but internally Homey uses (UU)IDs for every device. So if you remove a device and then re-add it, the device has given a new ID, and that is why the timer cannot be used anymore. 

It might be possible to add metadata to the timer, which I can try to use to find a new match when a given ID can't be found anymore, but this will take some time before I have time to fix that. However this seems more like a workaround for your original problem: Why do you need to re-add devices? I never remove my devices once they are included.

**Comment by shaarkys** [comment]
Hi @lvanderree , thank you so much for reply - actually there are two problems and maybe it's just one.
First I thought it happening after I rename the device. The reason for that was troubleshooting and updating then related flows, because when you remove device, Timer will not trough any error that device doesn't exist (eg. with RED exclamation mark). So it was for me "help" to recognize, which flows I have to update. And then I realized, I can't even update related Timers, because it will not provide me list of Timer capable devices.
But, later on I realized this is happening not just after renaming devices, but also for some other specifics - eg. I have Fibaro dimmer device - I add timer without issue, when I would like to change it/update it, the list is empty then and I have to re-create timer from scratch including all settings. To better ilustrate this, see screenshots for Yeelights - this is right selection window and see the selection window for Fibaro Dimmer device - it's empty and you can't select anything (uploading in new message)

**Comment by shaarkys** [comment]
**This is not OK**
![obrazek](https://user-images.githubusercontent.com/14859895/94656380-51ab5b80-0300-11eb-942f-8476b2eb5595.png)

**This is OK**
![obrazek](https://user-images.githubusercontent.com/14859895/94656414-5a039680-0300-11eb-8b5a-e3f5874fb9e0.png)

**Comment by shaarkys** [comment]
As I can replicate this problem, would it be possible to debug it maybe with sideload ? (but I guess it would have to be debug enabled version)
