### ISSUE TITLE
device not turning on when timer runs

### ISSUE THREAD

**Issue by OskarBrink** [lvanderree/com.synplyworks.thenmore#2]
I turned on the lamp with a timer. when I than turn the lamp off and do not cancel the timer, it is not possible to turn the lamp back on with the timer app.
I expect the timer to be ignored if the lamp is turned off and should be going on again. It looks like it only reacts properly when I also stop the timer when turning off the lamp.

**Comment by lvanderree** [comment]
Found a way to listen to the off events of devices, working on a stable implementation

**Comment by lvanderree** [comment]
Fixed in 0.6.0

**Comment by lvanderree** [comment]
It looks like the new API from Homey breaks this feature. Have to check into it again.

**Comment by lvanderree** [comment]
I guess this issue is fixed in 0.7+ versions
