### ISSUE TITLE
Homey pro 2023

### ISSUE THREAD

**Issue by nissenhj** [lvanderree/com.synplyworks.thenmore#23]
Will you update this app to work with the new Homey pro 2023?

**Comment by shaarkys** [comment]
Author already released first Test version, SKD3 ready

**Comment by stofferr** [comment]
Hi, any updates on this one? Homey are shipping the new HP2023 devices according to the community tracker, and an update of this app would be most welcome.

**Comment by nissenhj** [comment]
> 

https://homey.app/sv-se/app/com.synplyworks.thenmore/Timer/test/
