### ISSUE TITLE
Timer stopt te vroeg

### ISSUE THREAD

**Issue by SjaakKoning** [lvanderree/com.synplyworks.thenmore#6]
Bij het runnen van de timer stopt hij soms spontaan. Homey 1.5.
Bv nog 120 sec te gaan, gaat hij toch ineens uit. Trigger is een neo coolcam bewegingssensor. In de timer overzicht zie je hem dan ook opeens verdwijnen.

**Comment by lvanderree** [comment]
Hmm dat is vreemd, de "echte" timer die het apparaat uitzet staat eigenlijk los van de bijbehorende "virtuele" timer die je bij settings kan zien. Dus als zowel de timer verdwijnt bij settings en het apparaat niet uitgaat, is de enige logische verklaring die ik kan geven dat de app herstart (wellicht gecrashed) is. Ik heb (vermoedelijk) via homey 2 crash reports gezien, ik zal na mijn vakantie eens kijken of ik die ook aan deze bevinding kan relateren. De trigger (coolcam) staat hier sowieso los van

**Comment by MbenzNo** [comment]
I seem to have the same problem after upgrading to Homey 2.0. (If my dutch translation is correct...) App version 0.6.1 Beta. 
In Timer Management two of my 360 sec timers disappears after about 30 sec. One other 360 sec timer always completes.
The two flows where the timers disappears is causing the light not to be turned off.
The timer that is working is controlling a Fibaro2 dimmer. The timers that disappears is controlling a Qubino dimmer and a couple of switches (Everspring AN179)

**Comment by lvanderree** [comment]
I have updated the app (version 0.6.2). It is still waiting for approval of Athom, but can already get sideloaded via athom-cli tools. I think the issue was caused by the app crashing after a second trigger, which should now be fixed. Else please reopen this issue.
