### ISSUE TITLE
(lange) timers gaan niet terug naar "last state" maar uit

### ISSUE THREAD

**Issue by BWiltjer** [lvanderree/com.synplyworks.thenmore#7]
Ik gebruik timer om een gedimde lamp tijdelijk (via bewegingsmelder) naar een hogere dimstand te sturen. Dit werkt prima bij een instelling van een korte tijd, als ik de timer op de gewenste 10 minuten instel gaat de lamp echter niet terug naar de "last state" maar gewoon uit..

**Comment by BWiltjer** [comment]
Het blijkt dat bij een herhaalde trigger voordat de tijd is afgelopen, de timer wel wordt gereset, maar daarmee ook de waarde van de laatste dimstand verliest.

**Comment by lvanderree** [comment]
Top, daar kan ik wat mee. Zal er na mijn vakantie naar kijken

**Comment by lvanderree** [comment]
Ik heb een nieuwe versie gepushed (0.6.2) wacht nog op approval van Athom, maar kan al wel gesideload worden via athom-cli tools. Ik heb dit specifieke probleem nog niet hertest, maar wellicht werkt het nu, doordat ik caching heb aangepast

**Comment by lvanderree** [comment]
Ik heb nog wat fouten in 0.6.2 gezien, ben bezig aan een 0.7 versie, staat hier op github, maar met je email adres kan ik je ook aan de alpha testers toevoegen voor http://apps.athom.com

**Comment by lvanderree** [comment]
Ik denk dat dit issue nu opgelost is, in 0.7.2
Ik heb het zelf in ieder geval niet meer kunnen reproduceren. Mocht dit in 0.7.2 en verder toch nog voor komen, open dan aub het ticket weer. Het liefst weer met een beschrijving van de opstelling/instellingen/hoe te reproduceren
