### ISSUE TITLE
Tweede trigger stopt timer

### ISSUE THREAD

**Issue by RobVoogt** [lvanderree/com.synplyworks.thenmore#8]
Hallo,

Ik gebruik beta 6.1 i.c.m. R2.0 stable en het lijkt erop dat een tweede trigger binnen de tijd die staat ingesteld de timer laat verdwijnen. Alleen een herstart van de app lost het tijdelijk op totdat de situatie zich weer voordoet.

Rob

**Comment by lvanderree** [comment]
Ik heb een nieuwe versie gepushed (0.6.2) wacht nog op approval van Athom, maar kan al wel gesideload worden via athom-cli tools. De app crashte bij een 2e trigger, dat is nu gefixed, en daardoor moet dit nu werken
